# Documentation: https://docs.codecov.io/docs/codecov-yaml

codecov:
  # Avoid "Missing base report"
  # https://github.com/codecov/support/issues/363
  # https://docs.codecov.io/docs/comparing-commits
  allow_coverage_offsets: true

  # Avoid Report Expired
  # https://docs.codecov.io/docs/codecov-yaml#section-expired-reports
  max_report_age: off

coverage:
  # Explicitly control coverage status checks
  # https://docs.codecov.com/docs/commit-status#disabling-a-status
  status:
    project:
      default:
        # Use the coverage from the base commit (pull request base or parent commit) coverage to compare against
        target: auto
        # Allow the coverage to drop by X%
        threshold: 0.1%    
    patch: off
